CyrusNuevoDia/geocoder

- README.md
- lib/geocoder.ex
- lib/geocoder/providers/google_maps.ex
- lib/geocoder/store.ex
- lib/geocoder/worker.ex
This PR adds the possibility of passing geocoding parameters to the geocoding functions. This allows setting `language`, `key` (knrz/geocoder/issues/2) and any other of the parameters that are supported by the geocoding provider (`Geocoder.Provider.GoogleMaps`):
```elixir
[:key, :address, :components, :bounds, :language, :region, :latlng, :placeid, :result_type, :location_type]
```
Missing from this PR is the support of caching by fields other than `address` and `latlng`.
> Add the possibility of passing geocoding parameters to the geocoding functions

- README.md
- lib/geocoder/providers/google_maps.ex
… or any other option supported by `HTTPoison.get/3`
No tests, sorry, as this seems very difficult w/o stubbed network connections (see #13)
> Add proxy support

- lib/geocoder/worker.ex
When trying to configure timeouts larger than 30s, the GenServer default timeout will trigger before the poolboy one. This PR passes the timeout to the GenServer.call method, so that larger timeouts are possible.
I was thinking that it might be better to pass `opts[:timeout]` + some time to have the poolboy timeout hit first.
> Pass the configured timeout to the GenServer.call method

- config/config.exs
- lib/geocoder.ex
- lib/geocoder/providers/open_street_maps.ex
- lib/geocoder/worker.ex
- test/geocoder_test.exs
Another `geo` provider: [`OpenStreetMaps`](http://wiki.openstreetmap.org/wiki/Nominatim).
I did not find any chance to switch the provider in the runtime and I did not want to mix new provider code with anything else, that’s why testing might look a bit sloppy. Basically, the new `config` option is to be set to either `Google` or `OSM` and tests are to be run. This approach is by no means CI-friendly, though.
> OpenStreetMap provider: done.

- README.md
- lib/geocoder/worker.ex
- mix.exs
Resolves https://github.com/knrz/geocoder/issues/25
* Bumps minor version because this wasn't bumped after the inclusion of county geocoding
* Made the default provider Google instead of OpenStreetMaps to reflect what's in the docs (and also because the Google provider has a superset of the functionality of the OSM one).
* Update the README about configuration parameters and versions
> Correct documentation

- .travis.yml
Travis CI is broken still, though; see https://github.com/knrz/geocoder/pull/12#issuecomment-295731885
> Add Elixir v1.4 to build matrix

- lib/geocoder.ex
- lib/geocoder/store.ex
Removes Elixir 1.4 warnings in the style of:
```
warning: variable "pool_name" does not exist and is being expanded to "pool_name()", please use parentheses to remove the ambiguity or change the variable name
lib/geocoder.ex:21
```
> Remove ambiguity warnings

- lib/geocoder/providers/open_street_maps.ex
A list of results was matched aginst a wrong pattern. Also, OSM seems to use accept-language instead of language, so :langauge is mapped to :accept-language internally.
Sadly, I couldn't run the tests confidently because the "nominatim" online-service was not available (503).
> Fixed bug in OSM-Provider implemention. 

- config/config.exs
- lib/geocoder/providers/open_street_maps.ex
Since one need a API-Key since 11. Juni 2018 for `GoogleMaps` i changed to `OpenStreetMap` provider to run tests.  
Besides, I found a little bug in the `OpenStreetMaps` provider.
> Fix OpenStreetMap provider + use it to run tests

- .travis.yml
- README.md
- config/config.exs
- lib/geocoder.ex
- lib/geocoder/providers/google_maps.ex
- lib/geocoder/providers/open_cage_data.ex
- lib/geocoder/worker.ex
- test/geocoder_test.exs
* Major change is call-specific options are not supported and tested. They weren't working at all for me.
* Applied `mix format`
* Better docs on call-specific reporting
* Tests now pass on CI. Cut out some older CI versions and included new elixir versions.
* Fixed some deprecation warnings on Elixir 1.11
> Fixing call specific options

- lib/geocoder/providers/google_maps.ex
https://github.com/knrz/geocoder/compare/v0.6.2...master line 35 (now line 45 in master) of lib/geocoder/providers/google_maps.ex, used to use the old `Keyword.delete/3` which was deprecated and deleted a `:key` (second arg) for value (third arg); except when the code was updated to newer elixir which only has `Keyword.delete/2`, someone just got rid of the the third arg…. meaning instead of deleting `:latlng` when it was nil, it now always deletes the `:latlng` arg no matter what. The google provider on `1.0` does not work at all with just a `query` or with `:latlng` explicitly specified.
Please let me know if a `nil` check of the `:latlng` key is in fact necessary before dropping it as was previously the case. This change would allow `:latlng` set to default of `nil` to get through opt …
> do not delete latlng key always in google provder

- lib/geocoder/providers/open_street_maps.ex
#60 
I'm an elixir noob, so this may be a horrible way of fixing it 🤷 - feel free to bin or ammend - grabs the first element of the tuple returned from Float.parse (rather than using String.to_float)
> use Float.parse instead of String.to_float to avoid edge cases

- lib/geocoder/worker.ex
Since Elixir 1.12 there is a `Kernel` function called `tap/2`,
which conflicts with the `tap` from `Monad` (Towel)
> Add explicit module for `tap` call

- .formatter.exs
- .gitignore
- CODE_OF_CONDUCT.md
- LICENSE.md
- README.md
- mix.exs
Besides other documentation changes, this commit ensures the generated
HTML doc for HexDocs.pm will become the source of truth for this Elixir
library and leverage on latest features of ExDoc.
> Misc doc changes

- lib/geocoder/providers/open_street_maps.ex
In Australia suburbs are used instead of counties hence the OpenStreetMaps API returns a "suburb" field instead of "county". All this PR does is maps the suburb field to county in the Geocoder.Location map. Keeping it mapping to county prevents any need for changes elsewhere or in documentation.
> Add support for suburbs to OpenSteetMaps

- README.md
- config/config.exs
- lib/geocoder/providers/fake.ex
- test/geocoder_test.exs
Resolves #13
Adds configuration options similar to [Geolix.Adapter.Fake](https://github.com/elixir-geolix/geolix#fake-adapter) for configuring test mocks for calls to Geocoder.
I would definitely appreciate advice on approaches around the test suite changes as well as prime targets for refactoring.
> Add Geocoder.Providers.Fake

- README.md
- lib/geocoder/store.ex
PR based on #89 increasing the default precision to `6` and documenting the option in the readme.
> Increase precision default

- config/config.exs
- lib/geocoder/providers/google_maps.ex
- lib/geocoder/structs/coords.ex
- test/geocoder_test.exs
Add a parameter to know if a result is a partial match. This could be very useful since some applications (my case) needs the exact result for a location and currently there is no way to know if it is a partial match or not.
> Add partial_match on Geocoder Response

- .github/workflows/elixir.yml
- .gitignore
- README.md
- lib/geocoder/worker.ex
- mix.lock
- test/geocoder/store_test.exs
This was a tricky change for me to debug. Wanted to get your eyes on it before merging in:
- docs: update worker_config param for inline provider configuration
- dev: ignore elixir_ls for vs code users
- build: bump ssl_verify_fun so this runs on 1.15
- fix: inherit default worker_config when overwritting it
> default worker config

- .github/workflows/elixir.yml
- mix.exs
Mix.exs said support 1.10 but Matrix do not test for it
Mix.exs said support OTP 21, 22 and 23 but Matrix do not test for it
While it might work, those versions are not considered maintained much per https://hexdocs.pm/elixir/1.12/compatibility-and-deprecations.html
even more so https://hexdocs.pm/elixir/1.16.0/compatibility-and-deprecations.html#compatibility-between-elixir-and-erlang-otp
So proposing we bump a new version that allows to let the old stuff retire and force to a small set of version for a bit
what do you think?
> update minmum support for the library

- lib/geocoder/http_client/httpoison.ex
- test/geocoder/http_client/httpoison_test.exs
- Add pattern match for non-200 status codes in HTTPoison client
- Return raw response body for non-200 responses instead of attempting JSON decode
- Prevents crashes when APIs return status codes like 503 (timeout from OpenStreetMap)
- Add comprehensive tests to verify the fix works correctly
> Fix HTTPoison client to handle non-200 status codes

- CHANGELOG.md
- mix.exs
Updates version in mix.exs and adds changelog entry for HTTPoison client fix.
> Bump version to 2.2.2
